week3/pixtr/config/routes.rb
Rails.application.routes.draw do
  root to: "galleries#index" #sets root page

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :galleries do
    resources :images
    #resources :images, only: [:new, :create, :show]
  end

  #resources :galleries
  # get "/galleries" => "galleries#index"
  # get "/galleries/new" => "galleries#new" #must come before galleries/:id
  # get "/galleries/:id" => "galleries#show", as: :gallery #order here is important
  # post "/galleries" => "galleries#create"
  # delete "/galleries/:id" => "galleries#destroy"
  # get "/galleries/:id/edit" => "galleries#edit"
  # patch "/galleries/:id" => "galleries#update"
end

week3/pixtr/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images

  validates :name, presence: true #requires user to enter data in form
  validates :description, presence: true #requires user to enter data in form
end

week3/pixtr/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery

  validates :name, presence: true
  validates :description, presence: true
  validates :url, presence: true
end

week3/pixtr/app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
end

week3/pixtr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week3/pixtr/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def destroy
    gallery = Gallery.find(params[:id])
    gallery.destroy
    redirect_to galleries_path #path helper
  end

  def new
    @gallery = Gallery.new
  end

  def create
    Gallery.create(gallery_params)
    redirect_to "/galleries"
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    gallery = Gallery.find(params[:id])
    gallery.update(gallery_params)
    redirect_to "/galleries/#{gallery.id}"
  end

  private

  def gallery_params
    params.
    require(:gallery).
    permit(:name, :description)
  end
end

week3/pixtr/app/controllers/galleries_controller2.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def destroy
    gallery = Gallery.find(params[:id])
    gallery.destroy
    redirect_to galleries_path #path helper
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      redirect_to galleries_path
    else
      render :new
    end
  end

  def show
    @gallery = Gallery.find(params[:id])
    @images = @gallery.images #array of active record objects of 'image' instances (ActiveRecord::Associations:CollectionProxy)
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    gallery = Gallery.find(params[:id])
    gallery.update(gallery_params)
    redirect_to "/galleries/#{gallery.id}"
  end

  private

  def gallery_params
    params.
    require(:gallery).
    permit(:name, :description)
  end
end

week3/pixtr/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @gallery = find_gallery
    @image = Image.new
  end

  def create
    @gallery = find_gallery
    @image = @gallery.images.new(image_params)

    if @image.save   # tries to save image to database, if saves successfully returns true, else returns false
      redirect_to @gallery
    else  #if image is not saved because it didn't meet the validations
      render :new
    end
  end

  def show
    @gallery = find_gallery
    @image = find_image_in(@gallery)
  end

  def edit
    @gallery = find_gallery
    @image = find_image_in(@gallery)
  end

  def update
    @gallery = find_gallery
    @image = find_image_in(@gallery)
    if @image.update(image_params)
      redirect_to @gallery
    else
      render :edit
    end
  end

  def destroy
    gallery = find_gallery
    image = find_image_in(gallery)
    image.destroy

    redirect_to gallery
  end

  private

  def find_image_in(gallery)
    gallery.images.find(params[:id])
  end

  def find_gallery
    Gallery.find(params[:gallery_id])
  end

  def image_params
    params.
      require(:image).
      permit(:name, :description, :url)
  end
end

week3/pixtr/app/controllers/images_controller2.rb
class ImagesController < ApplicationController

  def new
    @gallery = find_gallery
    @image = Image.new
  end

  def create
    gallery = find_gallery

    gallery.images.create(image_params) #creating an image through the gallery, automatically creates an image and sets the gallery_id value to that of the gallery the image is created through.
    #creating the child image through the parent gallery - helps protect data

    redirect_to gallery # instead of redirect_to gallery_path(gallery)
  end

  def show
    @gallery = find_gallery
    @image = find_image_in(@gallery) #created a method to keep same layer of abstraction for both lines in this show action.
  end

  def edit
    @gallery = find_gallery
    @image = find_image_in(@gallery)
  end

  def update
    gallery = find_gallery
    image = find_image_in(gallery)
    image.update(image_params)

    redirect_to gallery
  end

  def destroy
    gallery = find_gallery
    image = find_image_in(gallery)
    image.destroy

    redirect_to gallery
  end

  private

  def image_params
    params.require(:image).permit(:name, :description, :url)
  end

  def find_gallery
    Gallery.find(params[:gallery_id])
  end

  def find_image_in(gallery)
    image = gallery.images.find(params[:id])
  end

end

week3/pixtr/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email]) # params needs the hash :session => :email
    cookies.signed[:user_id] = user.id #could user user.email or whatever 
    redirect_to galleries_path
  end
end

week3/pixtr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to galleries_path
    else render :new
    end
  end

  private 

  def user_params
    params.require(:user).permit(:email)
  end
end

week3/pixtr/app/helpers/application_helper.rb
module ApplicationHelper
end

week3/pixtr/app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <p>Could not save:</p>
  <ul>
    <% object.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
  </ul>
<% end %>

week3/pixtr/app/views/galleries/_form.html.erb
<%= render "errors", object: form.object %>

<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

week3/pixtr/app/views/galleries/_images.html.erb
<% @images.each do |image| %>
  <!-- <%= link_to image_tag(image.url, width: 200), [@gallery, image] %> --> <!-- can instead be written as a block, see below: -->

  <%= link_to [@gallery, image] do %>
    <%= image_tag image.url, width: 200 %>
  <% end %>

<%end %>

week3/pixtr/app/views/galleries/edit.html.erb
<h1>Edit <%= @gallery.name %></h1>

<%= form_for(@gallery) do |form| %>
  <%= render form %>
  <%= form.submit "Update Gallery" %>
<% end %>

week3/pixtr/app/views/galleries/edit.html2.erb
<h1>Edit <%= @gallery.name %></h1>

<%= form_for(@gallery) do |form| %>
  <%= render form %>
  <%= form.submit "Update Gallery" %>
<% end %>



<!--
<%= render "form" %>
-->

<!--
<%= form_for(@gallery) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <%= form.submit "Create" %>
<% end %>
-->

week3/pixtr/app/views/galleries/index.html.erb
<%= link_to "New Gallery", "/galleries/new" %> <!--action view helper method -->

<% @galleries.each do |gallery| %>
  <%= link_to gallery.name, "/galleries/#{gallery.id}" %>
<% end %>

week3/pixtr/app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= form_for(@gallery) do |form| %>
  <%= render form %>
  <%= form.submit "Create Gallery" %>
<% end %>

week3/pixtr/app/views/galleries/new.html2.erb
<h1>New Gallery</h1>

<%= form_for(@gallery) do |form| %>
  <%= render form %>
  <%= form.submit "Create Gallery" %>
<% end %>

<!--
<%= render "form" %>
-->

<!--
<%= form_for(@gallery) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <%= form.submit "Create" %>
<% end %>
-->


<!-- <form action="/galleries" method="POST">
  <input type="hidden" name="_method" value="put">
<div>
  <label>Enter Gallery Name: </label>
  <input type="text" name="gallery[name]">
</div>

<div>
  <label>Enter Gallery Description: </label>
  <input type="text" name="gallery[description]">
</div>

<div>
  <input type="submit" value="Create Gallery">
</div>
</form> -->

week3/pixtr/app/views/galleries/show.html.erb
<h1><%= @gallery.name %></h1>

<p><%= @gallery.description %></p>

<nav>
  <%= link_to "Edit", edit_gallery_path(@gallery) %>
  <%= link_to "Destroy", @gallery, method: :delete, data: { confirm: "Are you sure?" } %>
  <%= link_to "Add image", new_gallery_image_path(@gallery) %>
</nav>

<%= render @images %>

week3/pixtr/app/views/galleries/show.html2.erb
<h1><%= @gallery.name %></h1>
<p><%= @gallery.description %></p>

<nav>
<%= link_to "Edit", edit_gallery_path(@gallery) %>
<!-- <%= link_to "Edit", "/galleries/#{@gallery.id}/edit" %> -->

<%= link_to "Destroy", @gallery, method: :delete, data: { confirm: "are you sure?" } %>
<!-- <%= link_to "Destroy", "/galleries/#{@gallery.id}", method: :delete, data: { confirm: "are you sure?" } %> -->

<%= link_to "Add Image", new_gallery_image_path(@gallery) %>
<!-- <%= link_to "Add Image", "/galleries/#{@gallery.id}/images/new" %> -->
</nav>


<!--THIS-->
<%= render "images" %>

<!--DOES THE SAME AS THIS-->
<% @images.each do |image| %>
  <!-- <%= link_to image_tag(image.url, width: 200), [@gallery, image] %> --> <!-- can instead be written as a block, see below: -->

  <%= link_to [@gallery, image] do %>
    <%= image_tag image.url, width: 200 %>
  <% end %>

<%end %>

week3/pixtr/app/views/images/_form.html.erb
<%= render "errors", object: form.object %>

<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

<div>
  <%= form.label :url %>
  <%= form.text_field :url %>
</div>

week3/pixtr/app/views/images/_image.html.erb
<%= link_to [image.gallery, image] do %>
  <%= image_tag image.url, width: 200 -%>
<% end %>

week3/pixtr/app/views/images/edit.html.erb
<h1>Edit Image</h1>

<%= form_for([@gallery, @image]) do |form| %>
  <%= render form %>
  <%= form.submit "Update image" %>
<% end %>

week3/pixtr/app/views/images/edit2.html.erb
<h1>Edit Image</h1>

<%= form_for([@gallery, @image]) do |form| %>
  <%= render form %>
  <%= form.submit "Update image" %>
<% end %>


<!--
<%= render "images/form", { gallery: @gallery, image: @image } %>
-->

<!-- Alternate method using partials
<%= form_for([@gallery, @image]) do |form| %>
  <%= render form %>
  <%= form.submit "Update Image" %>
<% end %>
-->

<!-- Alternate method NOT using partials
<%= form_for([@gallery, @image]) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :url %>
  <%= form.text_field :url %>

  <%= form.submit "Update Image" %>
<% end %>
-->

week3/pixtr/app/views/images/new.html.erb
<%= form_for([@gallery, @image]) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_field :description %>

  <%= form.label :url %>
  <%= form.text_field :url %>

  <%= form.submit "Create" %>
<% end %>

week3/pixtr/app/views/images/new2.html.erb
<h1>New Image</h1>

<%= form_for([@gallery, @image]) do |form| %>
  <%= render form %>
  <%= form.submit "New image" %>
<% end %>

<!--
<%= render partial: "images/form", locals: { gallery: @gallery, image: @image } %> 
-->
<!--

<%= form_for([@gallery, @image]) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :url %>
  <%= form.text_field :url %>

  <%= form.submit %>
<% end %>

-->

week3/pixtr/app/views/images/show.html.erb
<nav>
  <%= link_to @gallery.name, @gallery %>
  <%= link_to "Edit image", edit_gallery_image_path(@gallery, @image) %>
  <%= link_to "Delete image", [@gallery, @image], method: :delete, data: {confirm: "Are you sure?" } %>
</nav>

<h1><%= @image.name %></h1>

<p><%= @image.description %></p>

<%= image_tag @image.url %>

week3/pixtr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixtr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "Sign in", new_session_path %>
  </div>
</br>

  <%= yield %>
</body>
</html>

week3/pixtr/app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= form_for(@user) do|form| %>
  <%= render "errors", object: form.object %>
  <%= form.label :email %>
  <%= form.email_field :email %>
  <%= form.submit "Sign up" %>
<% end %>